import { PageHeader } from '@/components/PageHeader';
import { getActiveRules, getEmployees, getEntities } from '@/lib/store';

export const dynamic = 'force-dynamic';

type Status = 'SYNTHETIC' | 'MOCKED' | 'REAL' | 'DETERMINISTIC' | 'AI';

const BADGE: Record<Status, { label: string; className: string }> = {
  SYNTHETIC: { label: 'Synthetic', className: 'bg-review-bg text-review ring-review/20' },
  MOCKED: { label: 'Mocked', className: 'bg-review-bg text-review ring-review/20' },
  REAL: { label: 'Real', className: 'bg-pass-bg text-pass ring-pass/20' },
  DETERMINISTIC: { label: 'Deterministic code', className: 'bg-pass-bg text-pass ring-pass/20' },
  AI: { label: 'AI', className: 'bg-accent-soft text-accent ring-accent/20' },
};

interface Row {
  item: string;
  status: Status;
  detail: string;
  production: string;
}

function Table({ title, blurb, rows }: { title: string; blurb: string; rows: Row[] }) {
  return (
    <section className="card overflow-hidden">
      <div className="card-head">
        <div>
          <h2 className="card-title">{title}</h2>
          <p className="card-sub">{blurb}</p>
        </div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full min-w-[820px] border-collapse">
          <thead className="border-b border-line bg-canvas">
            <tr>
              <th className="th w-[24%]">Component</th>
              <th className="th w-[13%]">Status</th>
              <th className="th w-[31%]">What it is in this build</th>
              <th className="th w-[32%]">What it would be in production</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-line">
            {rows.map((row) => (
              <tr key={row.item}>
                <td className="td font-medium text-ink">{row.item}</td>
                <td className="td">
                  <span
                    className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ring-1 ${BADGE[row.status].className}`}
                  >
                    {BADGE[row.status].label}
                  </span>
                </td>
                <td className="td">{row.detail}</td>
                <td className="td">{row.production}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export default async function ProvenancePage() {
  const entities = await getEntities();
  const employees = await getEmployees();
  const rules = await getActiveRules();

  const data: Row[] = [
    {
      item: 'Companies',
      status: 'SYNTHETIC',
      detail: `${entities.length} invented firms. Names, licence numbers, AUM and activities are fabricated to be plausible for GIFT IFSC.`,
      production: "Each company's own registration record, entered once at onboarding.",
    },
    {
      item: 'Employee records',
      status: 'SYNTHETIC',
      detail: `${employees.length} invented people, generated by scripts/generate-seed.mjs. Names, roles, qualifications, experience and certification dates are all fabricated.`,
      production: 'A feed from the entity’s HR or identity system, or a periodic CSV export from it.',
    },
    {
      item: 'Rule set',
      status: 'SYNTHETIC',
      detail: `${rules.length} rules hand-entered from real IFSCA instruments. The instruments are real; the clause references are indicative and the wording is paraphrased. Not verified line-by-line.`,
      production: 'Verified citation text, entered from the IFSCA handbook by a qualified person, or filed directly by the regulator through this same form.',
    },
    {
      item: 'The demo circular',
      status: 'SYNTHETIC',
      detail: 'IFSCA-FMD/2026/07 does not exist. It, and the sample circulars used to demonstrate the intake agents, were written for this prototype.',
      production: 'Circulars as published by IFSCA.',
    },
    {
      item: 'Discovery of new circulars',
      status: 'MOCKED',
      detail: 'A person finds the circular and pastes its text in. Nothing watches the IFSCA website.',
      production: 'A watcher on the IFSCA publications feed, queuing new documents for intake. Deliberately out of scope here.',
    },
    {
      item: 'Storage',
      status: 'MOCKED',
      detail: 'JSON files in /data. Readable and easy to reason about, but single-writer and with no transactions.',
      production: 'A database. src/lib/store.ts is the only file that would change.',
    },
    {
      item: 'Authentication',
      status: 'MOCKED',
      detail: 'None. Every visitor sees every company.',
      production: 'Per-company login, with an officer only ever seeing their own entity.',
    },
    {
      item: 'Notification delivery',
      status: 'MOCKED',
      detail: 'In-app only. The officer’s address is displayed but nothing is sent.',
      production: 'Email or webhook to the officer, with escalation if unacknowledged.',
    },
    {
      item: 'Evaluation date',
      status: 'MOCKED',
      detail: 'Pinned to 22 Aug 2026 in data/config.json so the demo is reproducible.',
      production: 'The current date, evaluated on a schedule so lapses surface the day they happen.',
    },
  ];

  const logic: Row[] = [
    {
      item: 'Matching engine',
      status: 'DETERMINISTIC',
      detail: 'src/lib/engine.ts. Field comparisons only. No AI, no RAG, no probability. Same data always gives the same answer.',
      production: 'Unchanged. This is the part that must never become a model.',
    },
    {
      item: '"Who newly failed" diff',
      status: 'DETERMINISTIC',
      detail: 'src/lib/impact.ts. Runs the engine before and after a rule change and compares per person.',
      production: 'Unchanged.',
    },
    {
      item: 'Schema validation of agent output',
      status: 'DETERMINISTIC',
      detail: 'validateDraft() in src/lib/agents.ts. Checks units, exact-match fields, enum membership, and whether a named certification exists on any roster. Cannot be argued with by either agent.',
      production: 'Unchanged, and extended as the rule schema grows.',
    },
    {
      item: 'Agent 1 — Drafting',
      status: 'AI',
      detail: 'Claude on AWS Bedrock. Reads a circular and proposes a structured rule, quoting the source for each field. Cannot save anything.',
      production: 'Same, plus PDF input and a queue fed by the publications watcher.',
    },
    {
      item: 'Agent 2 — Audit',
      status: 'AI',
      detail: 'Claude on AWS Bedrock. Re-reads the same document independently and attacks Agent 1’s draft. Cannot save anything.',
      production: 'Same. Worth running two auditors on high-impact rules and escalating on disagreement.',
    },
    {
      item: 'Impact memo',
      status: 'AI',
      detail: 'Optional. Rewrites a finding the engine already produced into prose. Falls back to template text when Bedrock is absent.',
      production: 'Same, optional.',
    },
    {
      item: 'Q&A box',
      status: 'AI',
      detail: 'Optional. Keyword retrieval over the rule texts, then an answer confined to those extracts. The only place retrieval is used.',
      production: 'Same, with proper retrieval once the rule set is large.',
    },
    {
      item: 'Human sign-off',
      status: 'REAL',
      detail: 'Two gates, both genuine: an officer files a rule only by submitting the form, and confirms a finding only by clicking confirm. No agent can complete either.',
      production: 'Unchanged, with the reviewer’s identity taken from their login rather than typed.',
    },
  ];

  return (
    <>
      <PageHeader
        title="What is real and what is not"
        subtitle="Every part of this build, and whether it is synthetic, mocked, deterministic code, or AI."
      />
      <div className="space-y-6 p-6">
        <div className="card border-l-[3px] border-l-accent px-5 py-4">
          <p className="text-[13px] leading-relaxed text-ink-body">
            This is a prototype. All the people and companies in it are invented, and no rule text
            here should be relied on as a compliance reference. What is real is the mechanism: the
            matching engine, the before/after diff, the two-agent intake with its deterministic
            check, and the two points where a human has to act.
          </p>
        </div>

        <Table
          title="Data"
          blurb="Where every number and name on the other pages came from."
          rows={data}
        />
        <Table
          title="Logic"
          blurb="Which parts are ordinary code, which are a language model, and which need a person."
          rows={logic}
        />

        <section className="card">
          <div className="card-head">
            <h2 className="card-title">The line we do not cross</h2>
          </div>
          <div className="card-body space-y-2 text-[13px] leading-relaxed text-ink-body">
            <p>
              AI reads documents. Code decides compliance. Those are separate by construction, not
              by convention — the engine has no model call in it and no path to one.
            </p>
            <p>
              An agent can propose a rule and never file it. The engine can flag a person and never
              conclude anything about them. Missing data is reported as{' '}
              <span className="font-medium text-review">needs review</span>, never as a failure. And
              every finding can be reproduced by hand from the rule and the record — which is what
              the <span className="font-medium text-accent">Engine self-check</span> page does, 50
              times over.
            </p>
          </div>
        </section>
      </div>
    </>
  );
}
